"""inital

Revision ID: c7156788651b
Revises: 
Create Date: 2017-05-11 14:09:07.835479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7156788651b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Node',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('ip_address', sa.Integer(), nullable=True),
    sa.Column('dat_start', sa.String(length=64), nullable=True),
    sa.Column('dat_end', sa.String(length=64), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.Column('permisson', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Node_ip_address'), 'Node', ['ip_address'], unique=True)
    op.create_index(op.f('ix_Node_name'), 'Node', ['name'], unique=False)
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('password_hash')
    )
    op.create_index(op.f('ix_User_email'), 'User', ['email'], unique=True)
    op.create_index(op.f('ix_User_first_name'), 'User', ['first_name'], unique=False)
    op.create_index(op.f('ix_User_last_name'), 'User', ['last_name'], unique=False)
    op.create_table('Association',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['Node.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'node_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Association')
    op.drop_index(op.f('ix_User_last_name'), table_name='User')
    op.drop_index(op.f('ix_User_first_name'), table_name='User')
    op.drop_index(op.f('ix_User_email'), table_name='User')
    op.drop_table('User')
    op.drop_index(op.f('ix_Node_name'), table_name='Node')
    op.drop_index(op.f('ix_Node_ip_address'), table_name='Node')
    op.drop_table('Node')
    # ### end Alembic commands ###
