"""empty message

Revision ID: f4f7ba65a00f
Revises: c7156788651b
Create Date: 2017-05-11 23:04:57.660334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4f7ba65a00f'
down_revision = 'c7156788651b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Node', sa.Column('permission', sa.Integer(), nullable=True))
    op.drop_column('Node', 'permisson')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Node', sa.Column('permisson', sa.INTEGER(), nullable=True))
    op.drop_column('Node', 'permission')
    # ### end Alembic commands ###
